// <auto-generated />
using EscolaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscolaApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250611233241_CriarTabelaEscola")]
    partial class CriarTabelaEscola
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EscolaApi.Models.Escola", b =>
                {
                    b.Property<string>("CodEscola")
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("CepEscola")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("CnpjEscola")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("NomeEscola")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("NumEnderecoEscola")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.HasKey("CodEscola");

                    b.ToTable("TB_ESCOLA", (string)null);

                    b.HasData(
                        new
                        {
                            CodEscola = "064",
                            CepEscola = "12345-678",
                            CnpjEscola = "62.823.257/0064-84",
                            NomeEscola = "Etec Professor Horácio Augusto da Silveira",
                            NumEnderecoEscola = "113"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
